site_name: make-responsive-images
site_description: Generate responsive images for your website, so you can use srcset in your <img> tags and serve an optimal image to each device that views your site.
site_url: https://mccarthysean.dev/make-responsive-images
repo_name: mccarthysean/make-responsive-images
repo_url: https://github.com/mccarthysean/make-responsive-images
edit_uri: ""
google_analytics:
  - G-Z6DZ02583Q
  - auto

# Use GitHub Pages theme instead with _config.yml file in folder?
# theme: mkdocs
theme:
  name: material
  # name: null
  # custom_dir: mkdocs-material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/favicon.ico

  palette:
    primary: light blue
    accent: indigo

nav:
  - make-responsive-images: index.md

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - extra