site_name: responsive-images-generator
site_description: Generate responsive images for your website, so you can use srcset in your <img> tags and serve an optimal image to each device that views your site.
site_url: https://github.com/mccarthysean/responsive-images-generator

theme:
    name: 'material'

repo_name: mccarthysean/responsive-images-generator
repo_url: https://github.com/mccarthysean/responsive-images-generator
edit_uri: ''

nav:
    - responsive-images-generator: 'index.md'
