site_name: make-responsive-images
site_description: Generate responsive images for your website, so you can use srcset in your <img> tags and serve an optimal image to each device that views your site.
site_url: https://mccarthysean.dev/make-responsive-images

# Use GitHub Pages theme instead with _config.yml file in folder?
# theme: mkdocs
theme:
    name: material
    palette:
      primary: light blue
      accent: indigo
    logo: img/ijack-logo.png
    favicon: img/favicon.ico

repo_name: mccarthysean/make-responsive-images
repo_url: https://github.com/mccarthysean/make-responsive-images
edit_uri: ""
google_analytics:
    - G-Z6DZ02583Q
    - auto

nav:
    - make-responsive-images: index.md

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - extra