name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Publish Docs
        run: |
          pip install mkdocs-material
          mkdocs gh-deploy --force --config-file ./mkdocs.yml
