name: Upload Package to PyPI

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        poetry-version: [1.8.3]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get full python version
        id: full-python-version
        run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")

      - name: Run image
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install Dependencies
        run: poetry install

      - name: Publish
        env:
            PYPI_TOKEN_PROD: ${{ secrets.PYPI_TOKEN_PROD }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN_PROD
          poetry run bash scripts/poetry_publish_package_prod.sh